{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "Customers_UpdateEntity"
	},
	"OnSuccess": "/FirstApp/Actions/CloseModalPage_Complete.action",
	"Target": {
		"Service": "/FirstApp/Services/FirstApp.service",
		"EntitySet": "Customers",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"EmailAddress": "#Control:FCEmail/#Value",
		"FirstName": "#Control:FCFirstName/#Value",
		"LastName": "#Control:FCCreateLastName/#Value",
		"PhoneNumber": "#Control:FCPhone/#Value"
	}
}